"use client";
import { ParallaxScroll } from "../ui/parallax-scroll";

export function ParallaxScrollDemo() {
  const images = [
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Alice Johnson",
      profile: "Software Developer",
      country: "USA",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "Michael Brown",
      profile: "Graphic Designer",
      country: "Canada",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Sophia Lee",
      profile: "Product Manager",
      country: "UK",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "David Miller",
      profile: "Marketing Specialist",
      country: "Australia",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    }, 
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Emily Davis",
      profile: "UX Researcher",
      country: "Germany",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "Oliver Martinez",
      profile: "Data Scientist",
      country: "Spain",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    }, 
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Charlotte Garcia",
      profile: "Business Analyst",
      country: "France",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "William Robinson",
      profile: "SEO Specialist",
      country: "Italy",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    }, 
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Amelia Martinez",
      profile: "Web Developer",
      country: "Mexico",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "Liam Johnson",
      profile: "Content Writer",
      country: "Japan",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    }, 
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Evelyn Moore",
      profile: "Project Manager",
      country: "Brazil",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "Lucas Taylor",
      profile: "Social Media Manager",
      country: "South Africa",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    }, 
    {
      src: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3387&q=80",
      username: "Mia Clark",
      profile: "Quality Assurance",
      country: "India",
      quote: "Innovate and elevate. Embrace the future with bold ideas.",
      flag: "https://restcountries.com/v3.1/all",
    },
    {
      src: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3070&q=80",
      username: "Henry Anderson",
      profile: "Digital Marketer",
      country: "New Zealand",
      quote: "Design is intelligence made visible. Creativity transforms.",
      flag: "https://restcountries.com/v3.1/all",
    }, 
  ];

  return <ParallaxScroll images={images} />;
}
